import type { Category } from '../types/category.js'

export const SYSTEM_CATEGORIES: Category[] = [
  {
    id: 'cat-supermarket-0001',
    userId: null,
    nameHe: 'סופרמרקט',
    icon: '🛒',
    color: '#22c55e',
    isSystem: true,
  },
  {
    id: 'cat-restaurants-0002',
    userId: null,
    nameHe: 'מסעדות',
    icon: '🍽️',
    color: '#f97316',
    isSystem: true,
  },
  {
    id: 'cat-coffee-000003',
    userId: null,
    nameHe: 'קפה',
    icon: '☕',
    color: '#a16207',
    isSystem: true,
  },
  {
    id: 'cat-clothing-00004',
    userId: null,
    nameHe: 'ביגוד',
    icon: '👕',
    color: '#8b5cf6',
    isSystem: true,
  },
  {
    id: 'cat-rent-000005',
    userId: null,
    nameHe: 'שכירות',
    icon: '🏠',
    color: '#3b82f6',
    isSystem: true,
  },
  {
    id: 'cat-car-0000006',
    userId: null,
    nameHe: 'רכב',
    icon: '🚗',
    color: '#6b7280',
    isSystem: true,
  },
  {
    id: 'cat-health-000007',
    userId: null,
    nameHe: 'בריאות',
    icon: '💊',
    color: '#ef4444',
    isSystem: true,
  },
  {
    id: 'cat-entertain-0008',
    userId: null,
    nameHe: 'בידור',
    icon: '🎬',
    color: '#ec4899',
    isSystem: true,
  },
  {
    id: 'cat-utilities-0009',
    userId: null,
    nameHe: 'חשמל ומים',
    icon: '⚡',
    color: '#eab308',
    isSystem: true,
  },
  {
    id: 'cat-education-0010',
    userId: null,
    nameHe: 'חינוך',
    icon: '📚',
    color: '#14b8a6',
    isSystem: true,
  },
  {
    id: 'cat-travel-000011',
    userId: null,
    nameHe: 'נסיעות',
    icon: '✈️',
    color: '#06b6d4',
    isSystem: true,
  },
  {
    id: 'cat-shopping-0012',
    userId: null,
    nameHe: 'קניות אונליין',
    icon: '📦',
    color: '#f59e0b',
    isSystem: true,
  },
  {
    id: 'cat-other-000013',
    userId: null,
    nameHe: 'אחר',
    icon: '💳',
    color: '#9ca3af',
    isSystem: true,
  },
]

export const OTHER_CATEGORY_ID = 'cat-other-000013'
