import type { CategoryRule } from '../types/category.js'

let ruleId = 1
const rule = (
  categoryId: string,
  pattern: string,
  patternType: CategoryRule['patternType'],
  priority = 0,
): CategoryRule => ({
  id: `rule-${String(ruleId++).padStart(4, '0')}`,
  userId: null,
  categoryId,
  pattern,
  patternType,
  priority,
  isSystem: true,
})

export const SYSTEM_CATEGORY_RULES: CategoryRule[] = [
  // סופרמרקט
  rule('cat-supermarket-0001', 'שופרסל', 'contains'),
  rule('cat-supermarket-0001', 'רמי לוי', 'contains'),
  rule('cat-supermarket-0001', 'ויקטורי', 'contains'),
  rule('cat-supermarket-0001', 'יינות ביתן', 'contains'),
  rule('cat-supermarket-0001', 'מגה', 'contains'),
  rule('cat-supermarket-0001', 'AM:PM', 'contains'),
  rule('cat-supermarket-0001', 'am pm', 'contains'),
  rule('cat-supermarket-0001', 'טיב טעם', 'contains'),
  rule('cat-supermarket-0001', 'סופרמרקט', 'contains'),
  rule('cat-supermarket-0001', 'SUPERMARKET', 'contains'),
  rule('cat-supermarket-0001', 'supermarket', 'contains'),
  rule('cat-supermarket-0001', 'יוחננוף', 'contains'),
  rule('cat-supermarket-0001', 'חצי חינם', 'contains'),
  rule('cat-supermarket-0001', 'כפר הירוק', 'contains'),
  rule('cat-supermarket-0001', 'SHUFERSAL', 'contains'),

  // מסעדות
  rule('cat-restaurants-0002', 'מקדונלדס', 'contains'),
  rule('cat-restaurants-0002', 'MCDONALDS', 'contains'),
  rule('cat-restaurants-0002', "מק'ד", 'contains'),
  rule('cat-restaurants-0002', 'בורגר קינג', 'contains'),
  rule('cat-restaurants-0002', 'BURGER KING', 'contains'),
  rule('cat-restaurants-0002', 'שווארמה', 'contains'),
  rule('cat-restaurants-0002', 'פיצה', 'contains'),
  rule('cat-restaurants-0002', 'PIZZA', 'contains'),
  rule('cat-restaurants-0002', 'דומינוס', 'contains'),
  rule('cat-restaurants-0002', 'פיצה האט', 'contains'),
  rule('cat-restaurants-0002', 'KFC', 'contains'),
  rule('cat-restaurants-0002', 'סושי', 'contains'),
  rule('cat-restaurants-0002', 'מסעדה', 'contains'),
  rule('cat-restaurants-0002', 'RESTAURANT', 'contains'),
  rule('cat-restaurants-0002', 'גוטה', 'contains'),
  rule('cat-restaurants-0002', 'רולדין', 'contains'),
  rule('cat-restaurants-0002', 'SUBWAY', 'contains'),
  rule('cat-restaurants-0002', 'TABOOLA', 'contains'),
  rule('cat-restaurants-0002', 'שקשוקיה', 'contains'),
  rule('cat-restaurants-0002', 'המבורגר', 'contains'),
  rule('cat-restaurants-0002', 'סטייק', 'contains'),
  rule('cat-restaurants-0002', 'STEAKHOUSE', 'contains'),

  // קפה
  rule('cat-coffee-000003', 'ארומה', 'contains', 1),
  rule('cat-coffee-000003', 'AROMA', 'contains', 1),
  rule('cat-coffee-000003', 'קפה נמרוד', 'contains', 1),
  rule('cat-coffee-000003', 'קפה גרג', 'contains', 1),
  rule('cat-coffee-000003', 'GREG', 'contains', 1),
  rule('cat-coffee-000003', 'STARBUCKS', 'contains', 1),
  rule('cat-coffee-000003', 'סטארבקס', 'contains', 1),
  rule('cat-coffee-000003', 'COFFEE', 'contains', 1),
  rule('cat-coffee-000003', 'קפה', 'contains', 1),
  rule('cat-coffee-000003', 'COFFEESHOP', 'contains', 1),
  rule('cat-coffee-000003', 'נספרסו', 'contains', 1),
  rule('cat-coffee-000003', 'NESPRESSO', 'contains', 1),
  rule('cat-coffee-000003', 'קפסולות', 'contains', 1),
  rule('cat-coffee-000003', 'בוסקי', 'contains', 1),

  // ביגוד
  rule('cat-clothing-00004', 'זארה', 'contains'),
  rule('cat-clothing-00004', 'ZARA', 'contains'),
  rule('cat-clothing-00004', 'H&M', 'contains'),
  rule('cat-clothing-00004', 'SHEIN', 'contains'),
  rule('cat-clothing-00004', 'פוקס', 'contains'),
  rule('cat-clothing-00004', 'FOX', 'contains'),
  rule('cat-clothing-00004', 'CASTRO', 'contains'),
  rule('cat-clothing-00004', 'קסטרו', 'contains'),
  rule('cat-clothing-00004', 'מנגו', 'contains'),
  rule('cat-clothing-00004', 'MANGO', 'contains'),
  rule('cat-clothing-00004', 'NIKE', 'contains'),
  rule('cat-clothing-00004', 'ADIDAS', 'contains'),
  rule('cat-clothing-00004', 'PULL&BEAR', 'contains'),
  rule('cat-clothing-00004', 'BERSHKA', 'contains'),
  rule('cat-clothing-00004', 'ביגוד', 'contains'),
  rule('cat-clothing-00004', 'נעליים', 'contains'),
  rule('cat-clothing-00004', 'TERMINAL X', 'contains'),

  // שכירות
  rule('cat-rent-000005', 'שכר דירה', 'contains', 2),
  rule('cat-rent-000005', 'שכירות', 'contains', 2),
  rule('cat-rent-000005', 'ועד בית', 'contains', 2),
  rule('cat-rent-000005', 'RENT', 'contains', 1),

  // רכב
  rule('cat-car-0000006', 'דלק', 'contains'),
  rule('cat-car-0000006', 'פנגו', 'contains'),
  rule('cat-car-0000006', 'PANGO', 'contains'),
  rule('cat-car-0000006', 'קנגורו', 'contains'),
  rule('cat-car-0000006', 'KANGAROO', 'contains'),
  rule('cat-car-0000006', 'טסטה', 'contains'),
  rule('cat-car-0000006', 'פז', 'startsWith'),
  rule('cat-car-0000006', 'דור אלון', 'contains'),
  rule('cat-car-0000006', 'DELEK', 'contains'),
  rule('cat-car-0000006', 'SONOL', 'contains'),
  rule('cat-car-0000006', 'סונול', 'contains'),
  rule('cat-car-0000006', 'ביטוח רכב', 'contains'),
  rule('cat-car-0000006', 'חניה', 'contains'),
  rule('cat-car-0000006', 'PARKING', 'contains'),
  rule('cat-car-0000006', 'טרמינל', 'contains'),
  rule('cat-car-0000006', 'WAZE', 'contains'),
  rule('cat-car-0000006', 'UBER', 'contains'),
  rule('cat-car-0000006', 'גט', 'contains'),
  rule('cat-car-0000006', 'GETT', 'contains'),
  rule('cat-car-0000006', 'YES GO', 'contains'),
  rule('cat-car-0000006', 'מוסך', 'contains'),

  // בריאות
  rule('cat-health-000007', 'מכבי', 'contains'),
  rule('cat-health-000007', 'מאוחדת', 'contains'),
  rule('cat-health-000007', 'כללית', 'contains'),
  rule('cat-health-000007', 'לאומית', 'contains'),
  rule('cat-health-000007', 'קופת חולים', 'contains'),
  rule('cat-health-000007', 'בית מרקחת', 'contains'),
  rule('cat-health-000007', 'סופר פארם', 'contains'),
  rule('cat-health-000007', 'SUPER-PHARM', 'contains'),
  rule('cat-health-000007', 'SUPERPHARM', 'contains'),
  rule('cat-health-000007', 'ביתא', 'contains'),
  rule('cat-health-000007', 'רופא', 'contains'),
  rule('cat-health-000007', 'PHARMACY', 'contains'),
  rule('cat-health-000007', 'CLINIC', 'contains'),
  rule('cat-health-000007', 'HOSPITAL', 'contains'),
  rule('cat-health-000007', 'בית חולים', 'contains'),
  rule('cat-health-000007', 'ד"ר', 'contains'),
  rule('cat-health-000007', 'OPTIKA', 'contains'),
  rule('cat-health-000007', 'שמיר אופטיקה', 'contains'),

  // בידור
  rule('cat-entertain-0008', 'HOT', 'contains'),
  rule('cat-entertain-0008', 'YES', 'contains'),
  rule('cat-entertain-0008', 'NETFLIX', 'contains'),
  rule('cat-entertain-0008', 'SPOTIFY', 'contains'),
  rule('cat-entertain-0008', 'APPLE', 'contains'),
  rule('cat-entertain-0008', 'GOOGLE PLAY', 'contains'),
  rule('cat-entertain-0008', 'STEAM', 'contains'),
  rule('cat-entertain-0008', 'סינמה', 'contains'),
  rule('cat-entertain-0008', 'CINEMA', 'contains'),
  rule('cat-entertain-0008', 'YES PLANET', 'contains'),
  rule('cat-entertain-0008', 'FLIX', 'contains'),
  rule('cat-entertain-0008', 'DISNEY', 'contains'),

  // חשמל ומים
  rule('cat-utilities-0009', 'חברת חשמל', 'contains'),
  rule('cat-utilities-0009', 'IEC', 'contains'),
  rule('cat-utilities-0009', 'מים', 'contains'),
  rule('cat-utilities-0009', 'גז', 'contains'),
  rule('cat-utilities-0009', 'BEZEQ', 'contains'),
  rule('cat-utilities-0009', 'בזק', 'contains'),
  rule('cat-utilities-0009', 'HOT NET', 'contains'),
  rule('cat-utilities-0009', 'אינטרנט', 'contains'),

  // חינוך
  rule('cat-education-0010', 'גן ילדים', 'contains'),
  rule('cat-education-0010', 'בית ספר', 'contains'),
  rule('cat-education-0010', 'אוניברסיטה', 'contains'),
  rule('cat-education-0010', 'מכללה', 'contains'),
  rule('cat-education-0010', 'UNIVERSITY', 'contains'),
  rule('cat-education-0010', 'COLLEGE', 'contains'),
  rule('cat-education-0010', 'שכר לימוד', 'contains'),
  rule('cat-education-0010', 'UDEMY', 'contains'),
  rule('cat-education-0010', 'COURSERA', 'contains'),

  // נסיעות
  rule('cat-travel-000011', 'EL AL', 'contains'),
  rule('cat-travel-000011', 'ELAL', 'contains'),
  rule('cat-travel-000011', 'אל על', 'contains'),
  rule('cat-travel-000011', 'BOOKING', 'contains'),
  rule('cat-travel-000011', 'AIRBNB', 'contains'),
  rule('cat-travel-000011', 'HOTELS', 'contains'),
  rule('cat-travel-000011', 'מלון', 'contains'),
  rule('cat-travel-000011', 'HOTEL', 'contains'),
  rule('cat-travel-000011', 'AIRPORT', 'contains'),
  rule('cat-travel-000011', 'נתב"ג', 'contains'),
  rule('cat-travel-000011', 'FLIGHT', 'contains'),

  // קניות אונליין
  rule('cat-shopping-0012', 'AMAZON', 'contains'),
  rule('cat-shopping-0012', 'ALIEXPRESS', 'contains'),
  rule('cat-shopping-0012', 'EBAY', 'contains'),
  rule('cat-shopping-0012', 'אמזון', 'contains'),
  rule('cat-shopping-0012', 'PAYPAL', 'contains'),
  rule('cat-shopping-0012', 'כיף', 'contains'),
  rule('cat-shopping-0012', 'IVORY', 'contains'),
]
